# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew desktop:dist

    # Download JRE for packr
    - name: Grant execute permission for download_JRE.sh
      working-directory: ./packr
      run: chmod +x download_JRE.sh
    - name: Download JRE for Packr
      working-directory: ./packr
      run: ./download_JRE.sh

    # Packr builds
    - name: Windows packr build
      working-directory: ./packr
      run: java -jar packr-all.jar windows.json
    - name: Mac packr build
      working-directory: ./packr
      run: java -jar packr-all.jar mac.json
    - name: Linux packr build
      working-directory: ./packr
      run: java -jar packr-all.jar linux.json

    # Zip packr builds
    - name: Zip windows build
      working-directory: ./packr/out/windows
      run: zip -r windows.zip ./windows
    - name: Zip mac build
      working-directory: ./packr/out/mac
      run: zip -r mac.zip ./mac
    - name: Zip linux build
      working-directory: ./packr/out/linux
      run: zip -r linux.zip ./linux

    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.1.2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          desktop/build/libs/desktop-1.0.jar
          packr/out/windows.zip
          packr/out/linux.zip
          packr/out/mac.zip

